name = "matrimony-backend"
compatibility_date = "2023-12-01"
workers_dev = true

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiM2I4MDUzOGEtOTYyMy00NDY4LTk0ODgtOGNmNTIxMDI3ZmRmIiwidGVuYW50X2lkIjoiODY2N2VkNDNjNGQzMGI4ZjI3NTI5MzM4YmI3ZGJkODVmNDQ5YTNiOTZlYTU2ZmY5Nzg3ODhhZjU5YmQ1NzRjNCIsImludGVybmFsX3NlY3JldCI6IjBjYzQ3YTNlLTFkZjctNDFhNy04YTdmLTQ5NzZlOGY1ZTZjZSJ9.n6PcvbyxdhQSqnZ2XFMJipUxpTyOHNEa7hq0SMDICSo"
JWT_SECRET = "parasbharde"
CLOUDINARY_CLOUDNAME = 'keepcoading'
CLOUDINARY_API_KEY = '759794822123685'
CLOUDINARY_API_SECRET = 'K_dtk0gZ-tN9gwlMQqdc7dWpKk8'




# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
